# -*- coding: utf-8 -*-
"""tfc lf0001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujtME96ZWUS5iVromfsD6jREf1sHUEN_
"""

import random
from collections import Counter

def simular_jogos_lotofacil(num_jogos):
    resultados = []
    for _ in range(num_jogos):
        jogo = random.sample(range(1, 26), 15)
        resultados.append(jogo)
    return resultados

def tabular_resultados(resultados):
    numeros = [num for jogo in resultados for num in jogo]
    contagem = Counter(numeros)
    for numero, frequencia in contagem.most_common():
        print(f"Número: {numero} - Frequência: {frequencia}")

# Simular e tabular 3 jogos da Lotofácil
resultados_lotofacil = simular_jogos_lotofacil(3)
tabular_resultados(resultados_lotofacil)

def tabular_resultados(resultados):
    for i, jogo in enumerate(resultados, start=1):
        print(f"Jogo {i}: {jogo}")
        numeros = jogo
        contagem = Counter(numeros)
        for numero, frequencia in contagem.most_common():
            print(f"Número: {numero} - Frequência: {frequencia}")
        print("\n")

# Simular e tabular 10 jogos da Lotofácil
resultados_lotofacil_10_jogos = simular_jogos_lotofacil(10)
tabular_resultados(resultados_lotofacil_10_jogos)

import random

numeros_mais_sorteados = [10, 11, 25, 13, 24, 14, 3, 4, 5, 12, 9, 1, 18, 2, 19]
numeros_menos_sorteados = [16, 15, 21, 7, 23, 6, 8, 22, 20]

def gerar_jogo_lotofacil():
    jogo = random.sample(numeros_mais_sorteados, 10) + random.sample(numeros_menos_sorteados, 5)
    return jogo

def gerar_10_jogos_lotofacil():
    jogos = [gerar_jogo_lotofacil() for _ in range(10)]
    return jogos

# Gerar e imprimir 10 jogos da Lotofácil
jogos_lotofacil = gerar_10_jogos_lotofacil()
for i, jogo in enumerate(jogos_lotofacil, start=1):
    print(f"Jogo {i}: {jogo}")

import random
import collections
from collections import Counter

def simular_jogos_lotofacil(quantidade_jogos):
    """Simula jogos da Lotofácil.

    Args:
        quantidade_jogos: Quantidade de jogos a serem simulados.

    Returns:
        Uma lista de jogos, onde cada jogo é uma lista de 15 números aleatórios.
    """

    jogos = []
    for _ in range(quantidade_jogos):
        jogo = random.sample(range(1, 26), 15)  # Sorteia 15 números de 1 a 25
        jogos.append(jogo)
    return jogos

def tabular_resultados(resultados):
    """Tabula os resultados dos jogos da Lotofácil.

    Args:
        resultados: Uma lista de jogos, onde cada jogo é uma lista de números.
    """

    for i, jogo in enumerate(resultados, start=1):
        print(f"Jogo {i}: {jogo}")
        numeros = jogo
        contagem = Counter(numeros)
        for numero, frequencia in contagem.most_common():
            print(f"Número: {numero} - Frequência: {frequencia}")
        print("\n")

# Simular e tabular 10 jogos da Lotofácil
resultados_lotofacil_10_jogos = simular_jogos_lotofacil(10)
tabular_resultados(resultados_lotofacil_10_jogos)